<a href="https://colab.research.google.com/github/PeterPirog/cars-regression/blob/main/01_analyze_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. Analyze original dataset

In [8]:
# Mounting google drive
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).

In [9]:
#! pip install openpyxl

In [10]:
# IMPORTS
import pandas as pd
# to display all the columns of the dataframe in the notebook
pd.pandas.set_option('display.max_rows', None,'display.max_columns', None)

import numpy as np
import os

In [11]:
if os.path.exists('helper_functions.py'):
    os.remove('helper_functions.py')
# Download helper functions script
!wget https://raw.githubusercontent.com/PeterPirog/cars-regression/main/helper_functions.py

--2022-02-13 16:28:07--  https://raw.githubusercontent.com/PeterPirog/cars-regression/main/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16499 (16K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  16.11K  --.-KB/s    in 0s

2022-02-13 16:28:07 (40.5 MB/s) - ‘helper_functions.py’ saved [16499/16499]

In [12]:
from helper_functions import test_function,dataframe_analysis
from helper_functions import TARGET, FEATURES_CATEGORICAL, FEATURES_NUMERICAL

In [13]:
FILE_PATH='/gdrive/MyDrive/datasets/cars/dataset.csv'
DIR_DATA='/gdrive/MyDrive/datasets/cars/'

# load dataset
df = pd.read_csv(FILE_PATH,delimiter=';')
df.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ID,Customer-ID,Estimate-ID,Service-ID,Scenario-Genre-ID,Version-Type-ID,Subject-ID,Publication datetime,Package,Amount,Status,Registration-date,Purchase-date,Import-status,Estimated-Vehicle-value,Subject-type,Load capacity,Maximum-mass,Mileage,Steering-wheel-side,LPG-system,Key-pairs,Younges-driver-age,Younges-driver-license-date,Parking-zip-code,Vehicle value,Production year,Brand,Model-type,Generation-type,Gearbox-type,Gears,Fuel-type,Capacity-ccm,Power-kW,Version-type-name,Body,Doors,Service-name,Ownership-mode,PESEL,License-issue-date,Marital-status,Place,Commune,County,Voivodeship,Customer-Contact-ZIP,TPL_POLICY_COUNT__7_YEAR,TPL_INSURANCE_PERIOD__5_YEAR,TPL_CLAIMS_COUNT__15_YEAR,TPL_CLAIMS_COUNT__14_YEAR,TPL_CLAIMS_COUNT__13_YEAR,TPL_CLAIMS_COUNT__12_YEAR,TPL_CLAIMS_COUNT__11_YEAR,TPL_CLAIMS_COUNT__10_YEAR,TPL_CLAIMS_COUNT__9_YEAR,TPL_CLAIMS_COUNT__8_YEAR,TPL_CLAIMS_COUNT__7_YEAR,TPL_CLAIMS_COUNT__6_YEAR,TPL_CLAIMS_COUNT__5_YEAR,TPL_CLAIMS_COUNT__4_YEAR,TPL_CLAIMS_COUNT__3_YEAR,TPL_CLAIMS_COUNT__2_YEAR,TPL_CLAIMS_COUNT__1_YEAR,TPL_CLAIMS_COUNT_PREVIOUS_YEAR,TPL_PREVIOUS_INSURANCE_COMPANY_PREVIOUS_YEAR,AC_POLICY_COUNT__7_YEAR,AC_INSURANCE_PERIOD__5_YEAR,AC_CLAIMS_COUNT__15_YEAR,AC_CLAIMS_COUNT__14_YEAR,AC_CLAIMS_COUNT__13_YEAR,AC_CLAIMS_COUNT__12_YEAR,AC_CLAIMS_COUNT__11_YEAR,AC_CLAIMS_COUNT__10_YEAR,AC_CLAIMS_COUNT__9_YEAR,AC_CLAIMS_COUNT__8_YEAR,AC_CLAIMS_COUNT__7_YEAR,AC_CLAIMS_COUNT__6_YEAR,AC_CLAIMS_COUNT__5_YEAR,AC_CLAIMS_COUNT__4_YEAR,AC_CLAIMS_COUNT__3_YEAR,AC_CLAIMS_COUNT__2_YEAR,AC_CLAIMS_COUNT__1_YEAR,AC_CLAIMS_COUNT_PREVIOUS_YEAR,AC_PREVIOUS_INSURANCE_COMPANY_PREVIOUS_YEAR,TPL_EVENTS_COUNT__15_YEAR,TPL_EVENTS_COUNT__14_YEAR,TPL_EVENTS_COUNT__13_YEAR,TPL_EVENTS_COUNT__12_YEAR,TPL_EVENTS_COUNT__11_YEAR,TPL_EVENTS_COUNT__10_YEAR,TPL_EVENTS_COUNT__9_YEAR,TPL_EVENTS_COUNT__8_YEAR,TPL_EVENTS_COUNT__7_YEAR,TPL_EVENTS_COUNT__6_YEAR,TPL_EVENTS_COUNT__5_YEAR,TPL_EVENTS_COUNT__4_YEAR,TPL_EVENTS_COUNT__3_YEAR,TPL_EVENTS_COUNT__2_YEAR,TPL_EVENTS_COUNT__1_YEAR,TPL_EVENTS_COUNT_PREVIOUS_YEAR,AC_EVENTS_COUNT__15_YEAR,AC_EVENTS_COUNT__14_YEAR,AC_EVENTS_COUNT__13_YEAR,AC_EVENTS_COUNT__12_YEAR,AC_EVENTS_COUNT__11_YEAR,AC_EVENTS_COUNT__10_YEAR,AC_EVENTS_COUNT__9_YEAR,AC_EVENTS_COUNT__8_YEAR,AC_EVENTS_COUNT__7_YEAR,AC_EVENTS_COUNT__6_YEAR,AC_EVENTS_COUNT__5_YEAR,AC_EVENTS_COUNT__4_YEAR,AC_EVENTS_COUNT__3_YEAR,AC_EVENTS_COUNT__2_YEAR,AC_EVENTS_COUNT__1_YEAR,AC_EVENTS_COUNT_PREVIOUS_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__15_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__14_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__13_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__12_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__11_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__10_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__9_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__8_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__7_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__6_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__5_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__4_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__3_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__2_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT__1_YEAR,AC_EVENTS_WHERE_CULPRIT_COUNT_PREVIOUS_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__15_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__14_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__13_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__12_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__11_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__10_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__9_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__8_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__7_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__6_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__5_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__4_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__3_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__2_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__1_YEAR,TPL_CLAIMS_WITHOUT_REFUSAL_COUNT_PREVIOUS_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__15_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__14_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__13_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__12_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__11_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__10_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__9_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__8_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__7_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__6_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__5_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__4_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__3_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__2_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT__1_YEAR,AC_CLAIMS_WITHOUT_REFUSAL_COUNT_PREVIOUS_YEAR,TPL_INSURANCE_COMPANIES_COUNT__5_YEAR,TPL_INSURANCE_COMPANIES_COUNT__10_YEAR,TPL_INSURANCE_COMPANIES_COUNT__15_YEAR,AC_INSURANCE_COMPANIES_COUNT__5_YEAR,AC_INSURANCE_COMPANIES_COUNT__10_YEAR,AC_INSURANCE_COMPANIES_COUNT__15_YEAR
0,41751547,64726,858275,33,38,21058,306458.0,2021-08-27 14:10:47.723262,p3,NaN,unavailable,1999-02-02,2020-08-26,a,NaN,a,NaN,NaN,1,l,a,2,0.0,NaN,34-604,NaN,1999,TOYOTA,Corolla,Corolla Sedan 97-00,m,5,b,1332,63,Linea Terra,sedan,4,ptuw,a,600225.0,NaN,other,Stronie,Łukowica,limanowski,małopolskie,34-604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41825353,46178,861617,33,38,18377,42421.0,2021-08-30 10:42:02.851606,p3,NaN,unavailable,1998-03-20,2021-08-30,b,NaN,a,NaN,NaN,310000,l,a,2,0.0,NaN,59-300,NaN,1998,TOYOTA,Corolla,Corolla Liftback 97-00,m,5,b,1332,63,Linea Terra,liftback,5,ptuw,a,750112.0,NaN,other,Niemstów,Lubin,lubiński,dolnośląskie,59-300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41825357,46178,861617,33,38,18377,42421.0,2021-08-30 10:42:03.606737,p4,NaN,unavailable,1998-03-20,2021-08-30,b,NaN,a,NaN,NaN,310000,l,a,2,0.0,NaN,59-300,NaN,1998,TOYOTA,Corolla,Corolla Liftback 97-00,m,5,b,1332,63,Linea Terra,liftback,5,ptuw,a,750112.0,NaN,other,Niemstów,Lubin,lubiński,dolnośląskie,59-300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,41825359,46178,861617,33,38,18377,42421.0,2021-08-30 10:42:04.341573,p5,NaN,unavailable,1998-03-20,2021-08-30,b,NaN,a,NaN,NaN,310000,l,a,2,0.0,NaN,59-300,NaN,1998,TOYOTA,Corolla,Corolla Liftback 97-00,m,5,b,1332,63,Linea Terra,liftback,5,ptuw,a,750112.0,NaN,other,Niemstów,Lubin,lubiński,dolnośląskie,59-300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,41825338,46178,861617,33,38,18377,42421.0,2021-08-30 10:42:00.908430,p1,933.0,success,1998-03-20,2021-08-30,b,NaN,a,NaN,NaN,310000,l,a,2,0.0,NaN,59-300,NaN,1998,TOYOTA,Corolla,Corolla Liftback 97-00,m,5,b,1332,63,Linea Terra,liftback,5,ptuw,a,750112.0,NaN,other,Niemstów,Lubin,lubiński,dolnośląskie,59-300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:

output,catCols,numCols=dataframe_analysis(df,xls_filename='Columns_analysis.xlsx')
FEATURES=FEATURES_CATEGORICAL+FEATURES_NUMERICAL
print(FEATURES)

['Body', 'Brand', 'Fuel-type', 'Gearbox-type', 'Generation-type', 'Import-status', 'LPG-system', 'Model-type', 'Ownership-mode', 'Package', 'Steering-wheel-side', 'Subject-type', 'Voivodeship', 'Marital-status', 'Version-type-name', 'AC_PREVIOUS_INSURANCE_COMPANY_PREVIOUS_YEAR', 'TPL_PREVIOUS_INSURANCE_COMPANY_PREVIOUS_YEAR', 'Commune', 'County', 'Customer-Contact-ZIP', 'Place', 'Parking-zip-code', 'Capacity-ccm', 'Doors', 'Gears', 'Key-pairs', 'Mileage', 'Power-kW', 'Younges-driver-age', 'AC_CLAIMS_COUNT__1_YEAR', 'AC_CLAIMS_COUNT__10_YEAR', 'AC_CLAIMS_COUNT__11_YEAR', 'AC_CLAIMS_COUNT__12_YEAR', 'AC_CLAIMS_COUNT__13_YEAR', 'AC_CLAIMS_COUNT__14_YEAR', 'AC_CLAIMS_COUNT__15_YEAR', 'AC_CLAIMS_COUNT__2_YEAR', 'AC_CLAIMS_COUNT__3_YEAR', 'AC_CLAIMS_COUNT__4_YEAR', 'AC_CLAIMS_COUNT__5_YEAR', 'AC_CLAIMS_COUNT__6_YEAR', 'AC_CLAIMS_COUNT__7_YEAR', 'AC_CLAIMS_COUNT__8_YEAR', 'AC_CLAIMS_COUNT__9_YEAR', 'AC_CLAIMS_COUNT_PREVIOUS_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__1_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__10_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__11_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__12_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__13_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__14_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__15_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__2_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__3_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__4_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__5_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__6_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__7_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__8_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT__9_YEAR', 'AC_CLAIMS_WITHOUT_REFUSAL_COUNT_PREVIOUS_YEAR', 'AC_EVENTS_COUNT__1_YEAR', 'AC_EVENTS_COUNT__10_YEAR', 'AC_EVENTS_COUNT__11_YEAR', 'AC_EVENTS_COUNT__12_YEAR', 'AC_EVENTS_COUNT__13_YEAR', 'AC_EVENTS_COUNT__14_YEAR', 'AC_EVENTS_COUNT__15_YEAR', 'AC_EVENTS_COUNT__2_YEAR', 'AC_EVENTS_COUNT__3_YEAR', 'AC_EVENTS_COUNT__4_YEAR', 'AC_EVENTS_COUNT__5_YEAR', 'AC_EVENTS_COUNT__6_YEAR', 'AC_EVENTS_COUNT__7_YEAR', 'AC_EVENTS_COUNT__8_YEAR', 'AC_EVENTS_COUNT__9_YEAR', 'AC_EVENTS_COUNT_PREVIOUS_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__1_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__10_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__11_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__12_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__13_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__14_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__15_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__2_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__3_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__4_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__5_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__6_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__7_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__8_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT__9_YEAR', 'AC_EVENTS_WHERE_CULPRIT_COUNT_PREVIOUS_YEAR', 'AC_INSURANCE_COMPANIES_COUNT__10_YEAR', 'AC_INSURANCE_COMPANIES_COUNT__15_YEAR', 'AC_INSURANCE_COMPANIES_COUNT__5_YEAR', 'AC_INSURANCE_PERIOD__5_YEAR', 'AC_POLICY_COUNT__7_YEAR', 'TPL_CLAIMS_COUNT__1_YEAR', 'TPL_CLAIMS_COUNT__10_YEAR', 'TPL_CLAIMS_COUNT__11_YEAR', 'TPL_CLAIMS_COUNT__12_YEAR', 'TPL_CLAIMS_COUNT__13_YEAR', 'TPL_CLAIMS_COUNT__14_YEAR', 'TPL_CLAIMS_COUNT__15_YEAR', 'TPL_CLAIMS_COUNT__2_YEAR', 'TPL_CLAIMS_COUNT__3_YEAR', 'TPL_CLAIMS_COUNT__4_YEAR', 'TPL_CLAIMS_COUNT__5_YEAR', 'TPL_CLAIMS_COUNT__6_YEAR', 'TPL_CLAIMS_COUNT__7_YEAR', 'TPL_CLAIMS_COUNT__8_YEAR', 'TPL_CLAIMS_COUNT__9_YEAR', 'TPL_CLAIMS_COUNT_PREVIOUS_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__1_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__10_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__11_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__12_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__13_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__14_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__15_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__2_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__3_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__4_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__5_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__6_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__7_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__8_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT__9_YEAR', 'TPL_CLAIMS_WITHOUT_REFUSAL_COUNT_PREVIOUS_YEAR', 'TPL_EVENTS_COUNT__1_YEAR', 'TPL_EVENTS_COUNT__10_YEAR', 'TPL_EVENTS_COUNT__11_YEAR', 'TPL_EVENTS_COUNT__12_YEAR', 'TPL_EVENTS_COUNT__13_YEAR', 'TPL_EVENTS_COUNT__14_YEAR', 'TPL_EVENTS_COUNT__15_YEAR', 'TPL_EVENTS_COUNT__2_YEAR', 'TPL_EVENTS_COUNT__3_YEAR', 'TPL_EVENTS_COUNT__4_YEAR', 'TPL_EVENTS_COUNT__5_YEAR', 'TPL_EVENTS_COUNT__6_YEAR', 'TPL_EVENTS_COUNT__7_YEAR', 'TPL_EVENTS_COUNT__8_YEAR', 'TPL_EVENTS_COUNT__9_YEAR', 'TPL_EVENTS_COUNT_PREVIOUS_YEAR', 'TPL_INSURANCE_COMPANIES_COUNT__10_YEAR', 'TPL_INSURANCE_COMPANIES_COUNT__15_YEAR', 'TPL_INSURANCE_COMPANIES_COUNT__5_YEAR', 'TPL_INSURANCE_PERIOD__5_YEAR', 'TPL_POLICY_COUNT__7_YEAR', 'Estimated-Vehicle-value', 'Maximum-mass', 'Load capacity']